### ISSUE TITLE
Nested models

### ISSUE THREAD

**Issue by nikolay-slavov** [RStankov/MiniForm#4]
Hi there, I need some help about nested models.
When I try to auto save nested models I have a problem.
The error that I get when I try to save with #update! method is:

**/Library/Ruby/Gems/2.0.0/gems/mini_form-0.1.0/lib/mini_form/nested_validator.rb:6:in `validate_each': undefined method `valid?' for {:balance=>"10000"}:**

To be clearer I'm giving you the following example:

```ruby
class User
  include ActiveModel::Model

  attr_accessor :name, :account

  validates :name, presence: true
end

class Account
  include ActiveModel::Model

  attr_accessor :balance

  validates :balance, presence: true
end

class TestForm
  include MiniForm::Model

  model :user, attributes: %i(name), save: true
  model :account, attributes: %i(balance), save: true

  def initialize
    @account = Account.new
    @user = User.new account: @account
  end
end

form = TestForm.new
form.update!({ name: 'Nikolay', account: { balance: '10000' } })
```

Is that the correct way to call #update! method for nested models, i.e. is the mapping of the key-value attributes ok?
The form is trying to call #valid? on account hash which is not ActiveModel.
I tried to overwrite #attributes=. It is not very pretty but it is only for the test.

```ruby
  def attributes=(attributes)
    attributes.slice(*self.class.attribute_names).each do |name, value|
      if self.class.models_to_save.include?(name.to_sym)
        value.each do |field_name, field_value|
          self.attributes[name.to_sym].public_send("#{field_name}=", field_value)
        end
      else
        public_send "#{name}=", value
      end
    end
  end
```

This way auto save works with nested models, otherwise in the context of the above example the account attribute is substituted with hash, and after that the #valid? method is called on it.

What am I doing wrong?

**Comment by RStankov** [comment]
Hi. Currently `MiniForm` doesn't support nested attributes. 

One work around you can do is to overwrite the setter for account:

```ruby
def account=(attributes)
   self.account.attributes = attributes
end
```

Usually I try not to have nested attributes and just have a flat argument list. But I will definitely think for a good solution for passing nested attributes.

**Comment by nikolay-slavov** [comment]
Thanks :)
